require("plugins.plugins-setup")

require("core.options")
require("core.keymaps")

require("plugins.lualine")
require("plugins.catppuccin")
require("plugins.nvim-tree")
require("plugins.rainbow-delimiters")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.gitstatus")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.toggleterm")
