# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "nvidia" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ 
  	nvidia_x11
#  	nvidiabl
  	lenovo-legion-module
  	];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.plymouth = rec {
        enable = true;
        # black_hud circle_hud cross_hud square_hud
        # circuit connect cuts_alt seal_2 seal_3
        theme = "connect";
        themePackages = with pkgs; [(
          adi1090x-plymouth-themes.override {
            selected_themes = [ theme ];
          }
        )];
      };
    

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/beca12dc-8907-4d9c-92f2-496da8d84331";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6CD8-72A4";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [
  	{device = "/dev/disk/by-uuid/c3ebba6d-6199-43b4-bb8f-b992df8c8a9d";}
      ];
  boot.resumeDevice = "/dev/disk/by-uuid/c3ebba6d-6199-43b4-bb8f-b992df8c8a9d";  # the unlocked drive mapping
  boot.kernelParams = [
    "resume_offset=0"
  ];
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp49s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable sound with pipewire.
    sound.enable = true;
    hardware.pulseaudio.enable = false;

  services.thermald.enable = true;

  # bluetooth
    hardware.bluetooth = {
      enable = true;
      powerOnBoot = true;
      settings.General.Experimental = true; # for gnome-bluetooth percentage
    };
}
