[[mgr.prepend_keymap]]
on   = [ "B", "a" ]
run  = 'plugin mactag --args="add"'
desc = "Tag selected files"

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on   = [ "B", "r" ]
run  = 'plugin mactag --args="remove"'
desc = "Untag selected files"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on = "`"
run = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"


[[mgr.prepend_keymap]]
on = "<C-s>"
run = '''
	shell 'open -R "$1"'
'''

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"'
'''

[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on = "k"
run = "plugin arrow --args=-1"

[[mgr.prepend_keymap]]
on = "j"
run = "plugin arrow --args=1"

[[mgr.prepend_keymap]]
on = "K"
run = "plugin parent-arrow --args=-1"

[[mgr.prepend_keymap]]
on = "J"
run = "plugin parent-arrow --args=1"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'qlmanage -p "$@"'
'''

[[mgr.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"
