# [[manager.prepend_keymap]]
# on = ["B", "r"]
# run = 'plugin mactag --args="add Red"'
# desc = "Tag selected files with red"

# [[manager.prepend_keymap]]
# on = ["B", "R"]
# run = 'plugin mactag --args="remove Red"'
# desc = "Remove red tag from selected files"

# [[manager.prepend_keymap]]
# on = ["B", "o"]
# run = 'plugin mactag --args="add Orange"'
# desc = "Tag selected files with orange"

# [[manager.prepend_keymap]]
# on = ["B", "O"]
# run = 'plugin mactag --args="remove Orange"'
# desc = "Remove orange tag from selected files"

# [[manager.prepend_keymap]]
# on = ["B", "g"]
# run = 'plugin mactag --args="add Green"'
# desc = "Tag selected files with green"

# [[manager.prepend_keymap]]
# on = ["B", "G"]
# run = 'plugin mactag --args="remove Green"'
# desc = "Remove green tag from selected files"

# [[manager.prepend_keymap]]
# on = ["B", "b"]
# run = 'plugin mactag --args="add Blue"'
# desc = "Tag selected files with blue"

# [[manager.prepend_keymap]]
# on = ["B", "B"]
# run = 'plugin mactag --args="remove Blue"'
# desc = "Remove blue tag from selected files"

# [[manager.prepend_keymap]]
# on = ["B", "p"]
# run = 'plugin mactag --args="add Purple"'
# desc = "Tag selected files with Purple"

# [[manager.prepend_keymap]]
# on = ["B", "P"]
# run = 'plugin mactag --args="remove Purple"'
# desc = "Remove purple tag from selected files"

# [[manager.prepend_keymap]]
# on = ["B", "y"]
# run = 'plugin mactag --args="add Yellow"'
# desc = "Tag selected files with yellow"

# [[manager.prepend_keymap]]
# on = ["B", "Y"]
# run = 'plugin mactag --args="remove Yellow"'
# desc = "Remove yellow tag from selected files"

# [[manager.prepend_keymap]]
# on = ["B", "h"]
# run = 'plugin mactag --args="add Grey"'
# desc = "Tag selected files with grey"

# [[manager.prepend_keymap]]
# on = ["B", "H"]
# run = 'plugin mactag --args="remove Grey"'
# desc = "Remove grey tag from selected files"

[[manager.prepend_keymap]]
on = "T"
run = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on = "`"
run = "plugin jump-to-char"
desc = "Jump to char"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"


[[manager.prepend_keymap]]
on = "<C-s>"
run = '''
	shell 'open -R "$1"'
'''

[[manager.prepend_keymap]]
on = ["g", "r"]
run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"'
'''

[[manager.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "run lazygit"

[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "Compress with ouch"

[[manager.prepend_keymap]]
on = ["u", "a"]
run = "plugin yamb --args=save"
desc = "Add bookmark"

[[manager.prepend_keymap]]
on = ["b"]
run = "plugin yamb --args=jump_by_key"
desc = "Jump bookmark by key"

[[manager.prepend_keymap]]
on = ["u", "g"]
run = "plugin yamb --args=jump_by_key"
desc = "Jump bookmark by key"

[[manager.prepend_keymap]]
on = ["u", "G"]
run = "plugin yamb --args=jump_by_fzf"
desc = "Jump bookmark by fzf"

[[manager.prepend_keymap]]
on = ["u", "d"]
run = "plugin yamb --args=delete_by_key"
desc = "Delete bookmark by key"

[[manager.prepend_keymap]]
on = ["u", "D"]
run = "plugin yamb --args=delete_by_fzf"
desc = "Delete bookmark by fzf"

[[manager.prepend_keymap]]
on = ["u", "A"]
run = "plugin yamb --args=delete_all"
desc = "Delete all bookmarks"

[[manager.prepend_keymap]]
on = ["u", "r"]
run = "plugin yamb --args=rename_by_key"
desc = "Rename bookmark by key"

[[manager.prepend_keymap]]
on = ["u", "R"]
run = "plugin yamb --args=rename_by_fzf"
desc = "Rename bookmark by fzf"

[[manager.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]
desc = "System Cilppad support"

[[manager.prepend_keymap]]
on = "k"
run = "plugin arrow --args=-1"

[[manager.prepend_keymap]]
on = "j"
run = "plugin arrow --args=1"

[[manager.prepend_keymap]]
on = "K"
run = "plugin parent-arrow --args=-1"

[[manager.prepend_keymap]]
on = "J"
run = "plugin parent-arrow --args=1"
