serverAddr = "222.186.10.250"
serverPort = 7000

[[proxies]]
name = "9987TCP"
type = "tcp"
localIP = "127.0.0.1"
localPort = 9987
remotePort = 9987


[[proxies]]
name = "9987UDP"
type = "udp"
localIP = "127.0.0.1"
localPort = 9987
remotePort = 9987

[[proxies]]
name = "30033TCP"
type = "tcp"
localIP = "127.0.0.1"
localPort = 30033
remotePort = 30033

[[proxies]]
name = "30033UDP"
type = "udp"
localIP = "127.0.0.1"
localPort = 30033
remotePort = 30033

[[proxies]]
name = "41144TCP"
type = "tcp"
localIP = "127.0.0.1"
localPort = 41144
remotePort = 41144

[[proxies]]
name = "41144UDP"
type = "udp"
localIP = "127.0.0.1"
localPort = 41144
remotePort = 41144

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 32

[[proxies]]
name = "port1TCP"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 65531

[[proxies]]
name = "port1UDP"
type = "udp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 65531

[[proxies]]
name = "CloudreveTCP"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5212
remotePort = 65532

[[proxies]]
name = "CloudreveUDP"
type = "udp"
localIP = "127.0.0.1"
localPort = 5212
remotePort = 65532


